server:
  port: 8090

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb?allowPublicKeyRetrieval=false&useSSL=false
    username: "root"
    password: "Super@2020"

  application:
    name: products-service
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

